version: '3'
services:
  database:
    # build:
    #   context: ./oh-core
    #   dockerfile: Dockerfile-ohdb
    image: oh-core_database:latest
    # ports:
    # - "3306:3306"
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1
    environment:
      MARIADB_MYSQL_LOCALHOST_USER: "true"
      MARIADB_DATABASE: oh
      MARIADB_ROOT_PASSWORD: ${OH_MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${OH_MARIADB_USER}
      MARIADB_PASSWORD: ${OH_MARIADB_PASSWORD}
    # volumes:
    #   - database_data:/var/lib/mysql
    networks:
      - hospital-net
    restart: unless-stopped
  
  oh-database-init:
    image: oh-core_database:latest
    command: sh -c "mysql -v --host database -u ${OH_MARIADB_USER} -p${OH_MARIADB_PASSWORD} oh < /database-sources/create_all_${OH_DEMO_LANG}.sql && mysql --host database -u ${OH_MARIADB_USER} -p${OH_MARIADB_PASSWORD} oh < /database-sources/load_demo_data.sql"
    working_dir: /database-sources
    environment:
      MARIADB_MYSQL_LOCALHOST_USER: "true"
      MARIADB_DATABASE: oh
      MARIADB_ROOT_PASSWORD: ${OH_MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${OH_MARIADB_USER}
      MARIADB_PASSWORD: ${OH_MARIADB_PASSWORD}
      DEMO_LANG: en
    volumes:
      - ./deps/openhospital-core/sql:/database-sources # /docker-entrypoint-initdb.d
    networks:
      - hospital-net

  connector:
    image: ${IMAGES_REPO}/ohpp-connector:${PATIENTPORTAL_VERSION}
    build:
      context: ./connector
      dockerfile: Dockerfile
      args:
        - OPENHOSPITAL_CORE_VERSION=${OPENHOSPITAL_CORE_VERSION}
    environment:
      - API_URL=develop-api.ohpp.local
#    networks:
#      - hospital-net
    network_mode: host

volumes:
  database_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATA_SHARED}/oh-database
    
networks:
  hospital-net:
    driver: bridge 
