global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
  
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  websecure-private:
    address: ":9443"
  ping:
    address: ":8082"

ping:
  entryPoint: "ping"

api: 
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic-config/"

